---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sorosutan/public_html/cobagit/
    - /bin/rm $DEPLOYPATHindex.php
    - /bin/rm -rf $DEPLOYPATHgambar
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R gambar $DEPLOYPATH
